title: Javier Arias
description: CS Graduate | Python & Data Enthusiast | GitHub Projects
logo: assets/imgs/20241202_223242.jpg
show_downloads: true
downloads: 
  - name: Resume
    file: assets/files/Resume.pdf
theme: jekyll-theme-minimal

